/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.jose.api_banco_local;

import java.awt.Color;
import java.util.List;
import org.apache.commons.dbcp2.BasicDataSource;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 *
 * @author Aluno
 */
public class TelaUsuario extends javax.swing.JFrame {

    private JdbcTemplate jdbcTemplateLocal;

    private JdbcTemplate jdbcTemplateAzure;

    void conexaoBancoLocal() {

        BasicDataSource dataSource = new BasicDataSource();
        dataSource.setDriverClassName("com.mysql.cj.jdbc.Driver");
        // exemplo para MySql: "com.mysql.cj.jdbc.Driver"
        dataSource.setUrl(
        "jdbc:mysql://localhost:3306/projetoapi?useTimezone=true&serverTimezone=UTC");
        // exemplo para MySql: "jdbc:mysql://localhost:3306/meubanco"
        dataSource.setUsername("ProjetoAPI");
        dataSource.setPassword("urubu100");

        jdbcTemplateLocal = new JdbcTemplate(dataSource);

    }

    void conexaoBancoAzure() {
        BasicDataSource dataSource = new BasicDataSource();
        dataSource.setDriverClassName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        dataSource.setUrl("jdbc:sqlserver://serverhumildificadores"
                + ".database.windows.net:1433;"
                + "database=bancohumildificadores;encrypt=true;"
                + "trustServerCertificate=false;"
                + "hostNameInCertificate=*.database.windows.net;");

        dataSource.setUsername("adminlocal");
        dataSource.setPassword("Safadinhos123@");
        
        jdbcTemplateAzure = new JdbcTemplate(dataSource);

    }

    /**
     * Creates new form TelaUsuario
     */
    public TelaUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        telaDados = new javax.swing.JFrame();
        userName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelUserDesktop = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelPlacaMae = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelCpuCount = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelClockOne = new javax.swing.JLabel();
        labelClockTwo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelMedCpuTemperature = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelCpuMediaPercent = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labelMedCpuClock = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labelMemoryLoad = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        labelMemoryUse = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        labelMemoryAvailable = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        labelVideoCard = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        inputUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputPass = new javax.swing.JPasswordField();
        loginIncorreto = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        telaDados.setMinimumSize(new java.awt.Dimension(941, 400));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setText("Aqui estão os dados da máquina:");

        jLabel6.setText("Id:");

        labelId.setText("-");

        jLabel8.setText("Usuário do desktop");

        labelUserDesktop.setText("-");

        jLabel7.setText("Placa mae:");

        labelPlacaMae.setText("-");

        jLabel9.setText("Contador de CPU:");

        labelCpuCount.setText("-");

        jLabel11.setText("1º Clock:");

        labelClockOne.setText("-");

        labelClockTwo.setText("2º Clock:");

        jLabel10.setText("-");

        jLabel12.setText("Media Temperatura da CPU:");

        labelMedCpuTemperature.setText("-");

        jLabel13.setText("Porcentagem de mídia da CPU:");

        labelCpuMediaPercent.setText("-");

        jLabel14.setText("Média de uso do Clock:");

        labelMedCpuClock.setText("-");

        jLabel15.setText("Carga de memória:");

        labelMemoryLoad.setText("-");

        jLabel17.setText("Memória em uso:");

        labelMemoryUse.setText("-");

        jLabel16.setText("Memória Disponível:");

        labelMemoryAvailable.setText("-");

        jLabel18.setText("Video Card:");

        labelVideoCard.setText("-");

        javax.swing.GroupLayout telaDadosLayout = new javax.swing.GroupLayout(telaDados.getContentPane());
        telaDados.getContentPane().setLayout(telaDadosLayout);
        telaDadosLayout.setHorizontalGroup(
            telaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(telaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userName)
                    .addComponent(jLabel5)
                    .addGroup(telaDadosLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelId))
                    .addGroup(telaDadosLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelUserDesktop))
                    .addGroup(telaDadosLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPlacaMae))
                    .addGroup(telaDadosLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCpuCount))
                    .addGroup(telaDadosLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelClockOne))
                    .addGroup(telaDadosLayout.createSequentialGroup()
                        .addComponent(labelClockTwo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(telaDadosLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelMedCpuTemperature))
                    .addGroup(telaDadosLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCpuMediaPercent))
                    .addGroup(telaDadosLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelMedCpuClock))
                    .addGroup(telaDadosLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelMemoryLoad))
                    .addGroup(telaDadosLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelMemoryUse))
                    .addGroup(telaDadosLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelMemoryAvailable))
                    .addGroup(telaDadosLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelVideoCard)))
                .addContainerGap(473, Short.MAX_VALUE))
        );
        telaDadosLayout.setVerticalGroup(
            telaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labelId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(labelUserDesktop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(labelPlacaMae))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(labelCpuCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(labelClockOne))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelClockTwo)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(labelMedCpuTemperature))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(labelCpuMediaPercent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(labelMedCpuClock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(labelMemoryLoad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(labelMemoryUse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(labelMemoryAvailable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(telaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(labelVideoCard))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Olá, seja bem vindo.");

        btnLogin.setText("Entrar");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel2.setText("Usuário:");

        jLabel4.setText("Senha:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(loginIncorreto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogin))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(inputUser))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(inputPass))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)))
                        .addGap(0, 78, Short.MAX_VALUE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(loginIncorreto))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        conexaoBancoLocal();
        conexaoBancoAzure();
        
        String user = inputUser.getText();
        String password = inputPass.getText();
        
        List<DadosBancoAzure> dadosAzure = 
        jdbcTemplateAzure.
        query("select * from cliente where email = ? and senha = ?",
        new BeanPropertyRowMapper(DadosBancoAzure.class), user, password);
        
        List<DadosBancoLocal> dadosLocal = 
        jdbcTemplateLocal.query("select * from pytohms", 
            new BeanPropertyRowMapper(DadosBancoLocal.class));
        
        if (dadosAzure.isEmpty()) {
            loginIncorreto.setText("Falha de auntenticação. Tente Novamente.");
            loginIncorreto.setForeground(Color.red);
        } else {
            telaDados.setVisible(true);
            DadosBancoAzure conexao = dadosAzure.get(0);
            userName.
                setText(
                String.format("Olá, seja bem vindo, %s", conexao.getNome()));
            userName.setForeground(Color.BLUE);
            DadosBancoLocal dados = dadosLocal.get(0);
            labelId.setText(dados.getId().toString());
            labelUserDesktop.setText(dados.getUser_desktop());
            labelPlacaMae.setText(dados.getPlaca_mae());
            labelCpuCount.setText(dados.getCpu_count().toString());
            labelClockOne.setText(dados.getClock_1());
            labelClockTwo.setText(dados.getClock_2());
            labelMedCpuTemperature.setText(dados.getCpu_media_temperatura());
            labelCpuMediaPercent.setText(dados.getCpu_media_percent());
            labelMedCpuClock.setText(dados.getCpu_media_clock());
            labelMemoryLoad.setText(dados.getMemory_load());
            labelMemoryUse.setText(dados.getMemory_use());
            labelMemoryAvailable.setText(dados.getMemory_available());
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JPasswordField inputPass;
    private javax.swing.JTextField inputUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelClockOne;
    private javax.swing.JLabel labelClockTwo;
    private javax.swing.JLabel labelCpuCount;
    private javax.swing.JLabel labelCpuMediaPercent;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelMedCpuClock;
    private javax.swing.JLabel labelMedCpuTemperature;
    private javax.swing.JLabel labelMemoryAvailable;
    private javax.swing.JLabel labelMemoryLoad;
    private javax.swing.JLabel labelMemoryUse;
    private javax.swing.JLabel labelPlacaMae;
    private javax.swing.JLabel labelUserDesktop;
    private javax.swing.JLabel labelVideoCard;
    private javax.swing.JLabel loginIncorreto;
    private javax.swing.JFrame telaDados;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
